In [66]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.5 or higher
tf.__version__

'2.8.2'

In [67]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [68]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [69]:
#reshape inputs for CNN layers
train_images=train_images.reshape(train_images.shape[0], 28, 28, 1)
test_images= test_images.reshape(test_images.shape[0], 28, 28, 1)

In [70]:
#lr decay function
#def learning_rate_decay(epoch):
  #return 0.01 * math.pow(0.6, epoch)

  #lr schedule callback
  #learning_rate_decay = tf.keras.callbacks.LearningRateScheduler(decay, verbose=True)
                                                  

In [71]:
#setup model
model = keras.Sequential([
    tf.keras.layers.Conv2D(kernel_size=3, filters=12, activation='relu', padding='same', use_bias=False),
    keras.layers.Conv2D(kernel_size=6, filters=24, activation='relu', padding='same', strides=1 ),
    keras.layers.Conv2D(32,6,2,'same', activation='relu'),
    keras.layers.Conv2D(32,6,2,'same', activation='relu'),
keras.layers.Flatten(),
    keras.layers.Dense(216, activation='relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(10, activation='softmax')

])
    


In [72]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [73]:

#train model

model.fit(train_images, train_labels, epochs=10, batch_size=60)

Epoch 1/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.1629 - accuracy: 0.9496
Epoch 2/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0553 - accuracy: 0.9835
Epoch 3/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0369 - accuracy: 0.9888
Epoch 4/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0297 - accuracy: 0.9907
Epoch 5/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0249 - accuracy: 0.9922
Epoch 6/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0212 - accuracy: 0.9935
Epoch 7/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0183 - accuracy: 0.9941
Epoch 8/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0139 - accuracy: 0.9957
Epoch 9/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0148 - accuracy: 0.9954
Epoch 10/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.012

In [74]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 1s 4ms/step - loss: 0.0262 - accuracy: 0.9935

Test accuracy: 0.9934999942779541


In [75]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

In [76]:
#Raw predictions
predictions

array([[1.32966981e-16, 4.22026940e-16, 1.62811591e-14, 1.20597724e-15,
        5.68046605e-16, 2.26386330e-17, 1.35150692e-22, 1.00000000e+00,
        1.00587561e-17, 1.94030578e-15],
       [5.26177799e-15, 5.87009460e-15, 1.00000000e+00, 3.64150131e-16,
        1.23404751e-17, 4.74215668e-22, 6.16969058e-15, 2.76303487e-17,
        8.09750961e-15, 2.89143697e-20],
       [2.53823893e-12, 1.00000000e+00, 4.15611885e-11, 8.67312187e-15,
        6.57589738e-12, 1.47860075e-11, 3.17998856e-11, 3.14211839e-08,
        3.33702649e-11, 6.16864476e-11],
       [1.00000000e+00, 1.01021061e-22, 2.69494391e-14, 3.06054526e-19,
        1.93637456e-20, 1.46384664e-18, 1.31365445e-13, 1.25315639e-16,
        2.47281043e-19, 1.53878848e-16],
       [3.84782772e-20, 2.50234742e-14, 5.29580417e-17, 2.24507516e-22,
        1.00000000e+00, 1.39836585e-15, 2.66716021e-15, 1.13839585e-14,
        2.33015736e-15, 1.60650132e-10]], dtype=float32)

In [77]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [78]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
